import { Metadata, PropertyMetadata } from './Metadata'
import { writeFile } from 'fs/promises'
import { writeFileSync } from 'fs'

export class EnvExampleGenerator {
  static saveEnvExample(schema: Function, path: string, sync: boolean) {
    const content = this.getEnvExampleContent(schema)

    const writeFunc = sync ? writeFileSync : writeFile

    return writeFunc(path, content, 'utf8')
  }

  private static getEnvExampleContent(schema: Function) {
    const meta = Metadata.forObject(schema.prototype)
    return this.header + this.renderProperties(meta.properties)
  }

  private static renderProperties(
    properties: Record<string, PropertyMetadata>
  ) {
    let text = ''

    for (const props of Object.values(properties)) {
      text += this.renderProperty(props)
    }

    return text.slice(0, text.length - 1)
  }

  private static get header() {
    const line1 = '# This file is autogenerated by env-plus'
    const line2 = '# Do not edit it manually'

    return `${line1}\n${line2}\n\n`
  }

  private static renderProperty(props: PropertyMetadata) {
    const required = props.default === undefined && props.required
    const requiredStr = required ? '[REQUIRED]' : '[OPTIONAL]'
    const valueStr = props.example ?? ''

    const line1 = `# ${requiredStr} ${props.description ?? ''}`
    const line2 = `${props.path}="${valueStr}"`

    return `${line1}\n${line2}\n\n`
  }
}
